name: 'Build check'

on: pull_request

jobs:
  publish:
    name: 'Build check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 14
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn docs
